language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

env:
  - DJANGO_VERSION="stable/1.4.x"
  - DJANGO_VERSION="stable/1.5.x"
  - DJANGO_VERSION="stable/1.6.x"
  - DJANGO_VERSION="stable/1.7.x"
  - DJANGO_VERSION="stable/1.8.x"
  - DJANGO_VERSION="master" # 1.9

install: 
   # This is a dependency of our Django test script
 - pip install argparse --use-mirrors

   # Install the dependencies of the app itself
   # - pip install -r requirements.txt --use-mirrors

   # Clone Django from the GitHub repository
 - git clone -b $DJANGO_VERSION --single-branch https://github.com/django/django
 - pip install -e django/

 - pip install coverage

 - pip install pep8 --use-mirrors
 - pip install pyflakes --use-mirrors

before_script:
    - "pep8 --ignore=E501 safedelete"
    - pyflakes safedelete

script:
    - coverage run quicktest.py safedelete

after_success:
 - pip install coveralls
 - coveralls


# We need to exclude old versions of Django for tests with python 3.
# We need to exclude old versions of Python for tests with Django >= 1.7.
# 1.9: Dropped support for 3.2-3.3: https://docs.djangoproject.com/en/dev/releases/1.9/#python-compatibility
matrix:
    exclude:
        - python: 3.2
          env: DJANGO_VERSION="stable/1.4.x"
        - python: 3.3
          env: DJANGO_VERSION="stable/1.4.x"
        - python: 3.4
          env: DJANGO_VERSION="stable/1.4.x"
        - python: 3.4
          env: DJANGO_VERSION="stable/1.5.x"
        - python: 3.4
          env: DJANGO_VERSION="stable/1.6.x"
        - python: 2.6
          env: DJANGO_VERSION="stable/1.7.x"
        - python: 2.6
          env: DJANGO_VERSION="stable/1.8.x"
        - python: 2.6
          env: DJANGO_VERSION="master"
        - python: 3.2
          env: DJANGO_VERSION="master"
        - python: 3.3
          env: DJANGO_VERSION="master"

